services:
  frontend:
    build: .
    container_name: beptyxa-frontend
    restart: unless-stopped
    ports:
      - "8443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - BACKEND_CONTAINER_NAME=${BACKEND_CONTAINER_NAME}
      - BACKEND_PORT=${BACKEND_PORT}
    networks:
      - beptyxa-network

networks:
  beptyxa-network:
    external: true